import { useEffect, useState } from 'react';
import { ArrowDown, ArrowRight, ArrowUpRight, ChevronDown, Code2, Cpu, Github, Globe2, Linkedin, Mail, Menu, Network, ShieldCheck, Terminal, X } from 'lucide-react';
import { contact, labs, projects, skillGroups } from './portfolio';
import IntroSplash from './components/IntroSplash';

const navigation = ['about', 'projects', 'labs', 'skills', 'contact'];
const categories = ['Embedded & IoT', 'Software', 'Networking', 'Academic'];
const icons = [ShieldCheck, Network, Code2, Cpu];
function Label({ number, children }: { number: string; children: string }) {
  return <p className="section-label"><span>{number} /</span> {children}</p>;
}

function App() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [activeSection, setActiveSection] = useState('home');
  const [filter, setFilter] = useState('All');
  useEffect(() => {
    const observer = new IntersectionObserver((entries) => {
      const visible = entries.filter((entry) => entry.isIntersecting).sort((a, b) => b.intersectionRatio - a.intersectionRatio);
      if (visible[0]) setActiveSection(visible[0].target.id);
    }, { rootMargin: '-15% 0px -45% 0px', threshold: [0, 0.2, 0.5] });
    document.querySelectorAll('main > section[id]').forEach((section) => observer.observe(section));
    return () => observer.disconnect();
  }, []);
  useEffect(() => {
    if (!menuOpen) return;
    const close = (event: KeyboardEvent) => {
      if (event.key === 'Escape') {
        setMenuOpen(false);
        document.getElementById('menu-toggle')?.focus();
      }
    };
    window.addEventListener('keydown', close);
    return () => window.removeEventListener('keydown', close);
  }, [menuOpen]);

  return <div className="site-shell">
    <IntroSplash name="Christian Jade Villaver" />
    <a className="skip-link" href="#main">Skip to content</a>
    <header className="topbar">
      <a className="brand" href="#home" onClick={() => setMenuOpen(false)} aria-label="Christian Jade Villaver home"><span className="brand-mark">cj<span>.</span></span><span>CHRISTIAN JADE<br /><small>VILLAVER / CPE PROFESSIONAL</small></span></a>
      <nav id="main-navigation" className={`nav-links ${menuOpen ? 'open' : ''}`} aria-label="Main navigation">{navigation.map((item) => <a key={item} href={`#${item}`} className={activeSection === item ? 'active' : ''} aria-current={activeSection === item ? 'location' : undefined} onClick={() => setMenuOpen(false)}>{item === 'labs' ? 'Experience' : item}</a>)}</nav>
      <a href="#contact" className="header-contact">Let’s connect <ArrowUpRight size={15} /></a>
      <button id="menu-toggle" className="menu-toggle" aria-expanded={menuOpen} aria-controls="main-navigation" aria-label={menuOpen ? 'Close menu' : 'Open menu'} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button>
    </header>
    <main id="main">
      <section id="home" className="hero section-wrap">
        <div className="hero-copy"><p className="eyebrow"><span className="status-dot" /> OPEN TO OPPORTUNITIES</p><p className="hero-name">COMPUTER ENGINEERING PROFESSIONAL</p><h1>Understand.<br />Build.<br /><span>Secure.</span></h1><p className="hero-intro">Hands-on experience across <strong>IT support, networking, software development, embedded systems, and IoT,</strong> with a growing focus on infrastructure, cybersecurity, and practical technology solutions.<br /><small>In a world full of the common, dare to be uncommon.</small></p><div className="button-row"><a className="button primary" href="#projects">Explore my work <ArrowUpRight size={18} /></a><a className="text-link" href="#about">A little about me <ArrowRight size={16} /></a></div><div className="hero-meta"><span><Globe2 size={14} /> BASED IN THE PHILIPPINES</span><span>BS COMPUTER ENGINEERING</span></div></div>
        <div className="hero-visual"><div className="visual-caption"><span>FIG. 01 — A CONNECTED MINDSET</span><span className="green-text">SYSTEM ONLINE <span className="status-dot" /></span></div><div className="network-diagram" role="img" aria-label="Computer Engineering connects IT support, networking, software development, embedded systems, and IoT."><div className="orbit orbit-outer" /><div className="orbit orbit-inner" /><div className="diagram-axis horizontal" /><div className="diagram-axis vertical" /><svg className="network-lines" viewBox="0 0 500 420" aria-hidden="true"><path d="M250 70 L250 210 L80 210 M250 210 L420 210 M250 210 L250 350" /><circle cx="250" cy="135" r="3" /><circle cx="335" cy="210" r="3" /><circle cx="165" cy="210" r="3" /><circle cx="250" cy="285" r="3" /></svg><div className="core-node"><Cpu size={35} strokeWidth={1.3} /><strong>CJ<span>_</span></strong><small>CPE PROFESSIONAL</small></div><div className="network-node node-top"><ShieldCheck size={20} /><span>IOT</span></div><div className="network-node node-left"><Network size={20} /><span>NETWORKS</span></div><div className="network-node node-right"><Code2 size={20} /><span>SOFTWARE</span></div><div className="network-node node-bottom"><Terminal size={20} /><span>EMBEDDED</span></div><span className="diagram-coordinate">UNDERSTAND END TO END.<br />BUILD PRACTICAL SOLUTIONS.</span><span className="diagram-version">PROFILE v.01</span></div><div className="terminal"><div className="terminal-bar"><span><i /><i /><i /></span><span>christian@portfolio: ~</span><Terminal size={13} /></div><div className="terminal-body"><p><span>❯</span> cat mindset.txt</p><p className="terminal-output">Understand systems end to end.<br />Keep learning. Build practical technology.</p><p><span>❯</span> <i className="cursor" /></p></div></div></div>
        <div className="hero-bottom"><a href="#about"><ArrowDown size={14} /> SCROLL TO EXPLORE</a><span>ALWAYS LEARNING. ALWAYS ITERATING.</span></div>
      </section>
      <div className="focus-strip"><div className="section-wrap"><span>AREAS OF FOCUS</span><p><ShieldCheck /> Embedded &amp; IoT</p><i>+</i><p><Network /> Networking</p><i>+</i><p><Terminal /> IT support</p><i>+</i><p><Code2 /> Software</p></div></div>
      <section id="about" className="section-wrap about-section"><div><Label number="01">THE PERSON BEHIND THE TERMINAL</Label><h2>Computer Engineering professional<br /><span>focused on practical technology.</span></h2></div><div className="about-copy"><p className="lead">I am a Computer Engineering professional with hands-on exposure to IT support, networking, software development, embedded systems, and Internet of Things technologies.</p><p>My experience includes working as an IT Assistant during my On-the-Job Training, where I gained practical exposure to real workplace IT environments and strengthened my troubleshooting, technical support, communication, and problem-solving skills.</p><p>My academic and technical projects have also allowed me to work across both hardware and software. I have worked with microcontrollers, sensors, wireless communication, web technologies, databases, and networking concepts while developing practical engineering solutions.</p><p>One of my current technical projects focuses on an Occupancy-Driven Plug for Adaptive Lighting and Appliance Control, integrating technologies such as ESP8266, ESP32-C3, occupancy and ambient-light sensors, ESP-NOW communication, and mobile-based monitoring and control. The project reflects my interest in IoT, automation, embedded systems, and practical energy-management solutions.</p><p>I am continuing to develop my skills in networking, IT infrastructure, cybersecurity, software development, and emerging technologies. My goal is to build a career where I can apply my Computer Engineering background to practical IT and technology problems while continuously improving my technical capabilities.</p><div className="about-facts"><div><span>EDUCATION</span><strong>Bachelor of Science in Computer Engineering<br />University of Cebu</strong><p className="publication-note">Relevant coursework and thesis/research: details to be added. Academic projects are listed below.</p></div><div><span>NEXT CHAPTER</span><strong><span className="status-dot" /> Open to entry-level roles</strong></div></div></div></section>
      <section id="projects" className="section-wrap"><div className="section-heading"><div><Label number="02">THE WORKBENCH</Label><h2>Ideas into <span>practice.</span></h2></div><p>Hardware, software, and networking projects.<br />Additional academic work: details to be added.</p></div><div className="project-toolbar"><div className="filters" role="group" aria-label="Filter projects">{['All', ...categories].map((category) => <button key={category} aria-pressed={filter === category} onClick={() => setFilter(category)} className={filter === category ? 'selected' : ''}>{category}{category === 'All' && <span>04</span>}</button>)}</div><span className="micro-label" aria-live="polite">{filter === 'All' ? '04' : '01'} WORK &amp; LEARNING AREAS</span></div><div className="project-grid">{projects.map((project, index) => {
        const Icon = icons[index];
        if (filter !== 'All' && filter !== categories[index]) return null;
        return <article className="project-card" key={project.title}><div className={`project-art art-${index}`} aria-hidden="true"><div className="art-grid" /><span className="art-id">CJ / 0{index + 1}</span><div className="art-symbol"><Icon size={45} strokeWidth={1} /></div><span className="art-label">{['CONNECTED DEVICES', 'WEB-BASED MANAGEMENT', 'BUILDING FOUNDATIONS', 'ACADEMIC PROJECT PLACEHOLDER'][index]}</span><span className="art-corner">+</span></div><div className="project-content"><div className="card-top"><span>{project.category}</span><span className={`project-status ${project.status === 'IN PROGRESS' ? 'in-progress' : ''}`}><span />{project.status === 'ARCHIVED' ? 'DOCUMENTATION PENDING' : project.status}</span></div><h3>{project.title}</h3><p>{project.description}</p><div className="tag-row">{project.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><details className="project-details"><summary>Scope &amp; context <ChevronDown size={16} /></summary><div><p>{project.scope}</p><p className="publication-note">{project.status === 'PLACEHOLDER' ? 'Placeholder — project information not yet provided.' : 'Practical projects and continued technical learning.'}</p></div></details></div></article>;
      })}</div></section>
      <section id="labs" className="section-wrap"><div className="section-heading"><div><Label number="03">EXPERIENCE &amp; LEARNING</Label><h2>Across disciplines.<br /><span>Deeper understanding.</span></h2></div><p>IT support experience and ongoing projects.<br />Networking and cybersecurity skills in development.</p></div><div className="lab-list">{labs.map((lab, index) => <details className="lab-row" key={lab.title}><summary><span className="lab-number">0{index + 1}</span><span className="lab-title">{lab.title}<small>{lab.category}</small></span><span className="lab-state">{lab.status}</span><ChevronDown size={19} /></summary><div className="lab-description"><p>{lab.description}</p>{lab.responsibilities && <ul>{lab.responsibilities.map((responsibility) => <li key={responsibility}>• {responsibility}</li>)}</ul>}<span>FOCUS / {lab.tools}</span><p className="publication-note">Part of my ongoing technical development.</p></div></details>)}</div></section>
      <section id="skills" className="section-wrap"><div className="section-heading"><div><Label number="04">TOOLS OF THE TRADE</Label><h2>A growing <span>toolkit.</span></h2></div><p>Hands-on technical exposure, with networking<br />and cybersecurity foundations in development.</p></div><div className="skills-grid">{skillGroups.map(([group, skills], index) => <div className="skill-group" key={group}><span className="skill-index">0{index + 1} /</span><h3>{group}</h3><div>{skills.map((skill) => <span className="skill-chip" key={skill}>{skill}</span>)}</div></div>)}</div><div className="learning-line"><span className="status-dot" /><span>CURRENTLY EXPLORING</span><p>Networking &amp; IT infrastructure <b>/</b> Cybersecurity <b>/</b> Software <b>/</b> Embedded systems &amp; IoT <b>/</b> Emerging technologies</p></div></section>
      <section id="contact" className="section-wrap contact-section"><div><Label number="05">WHAT’S NEXT?</Label><h2>Let’s build<br /><span>practical technology.</span></h2><p>I’m currently open to entry-level opportunities where I can apply my Computer Engineering background, contribute to technical teams, and continue developing my skills across IT, networking, software, embedded systems, and cybersecurity.</p>{contact.email ? <a className="button primary" href={`mailto:${contact.email}`}>Let’s talk <ArrowUpRight size={18} /></a> : <p className="contact-pending"><Mail size={17} /> Contact details will be available here soon.</p>}</div><div className="contact-aside"><span className="availability"><span className="status-dot" /> OPEN TO WORK</span><p>Based in the Philippines.<br />Ready for the next challenge.</p><div className="social-links">{contact.github && <a href={contact.github} target="_blank" rel="noreferrer"><Github size={18} /> GitHub <ArrowUpRight size={16} /></a>}{contact.linkedin && <a href={contact.linkedin} target="_blank" rel="noreferrer"><Linkedin size={18} /> LinkedIn <ArrowUpRight size={16} /></a>}</div></div></section>
    </main>
    <footer className="footer section-wrap"><a className="brand-mark" href="#home" aria-label="Back to top">cj<span>.</span></a><span>© {new Date().getFullYear()} Christian Jade Villaver</span><span>BUILT WITH CURIOSITY & PURPOSE</span><a href="#home">Back to top <ArrowUpRight size={14} /></a></footer>
  </div>;
}
export default App;
